version: '3'

networks:
  sample_laravel: 
services:
  nginx_laravel: 
    image: nginx:stable-alpine
    container_name: nginx_laravel
    ports: 
      - "8088:80"
    volumes:
      - ./src:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - laravel_php
      - laravel_mysql
    networks:
      - sample_laravel

  laravel_mysql:
    image: mysql:5.7
    container_name: laravel_mysql
    restart: unless-stopped
    tty: true
    volumes:
      - ./mysql:/var/lib/mysql
    ports:
      - "4036:3036"
    environment:
      MYSQL_DATABASE: sample_laravel
      MYSQL_USER: homestead
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: secret
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    networks:
      - sample_laravel
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    restart: unless-stopped
    environment:
      PMA_HOST: laravel_mysql
      PMA_USER: homestead
      PMA_PASSWORD: secret
    ports:
      - "8080:80"
    networks:
      - sample_laravel
  laravel_php:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: laravel_php
    
    restart: unless-stopped
    tty: true
    volumes: 
      - ./src:/var/www/html
    working_dir: /var/www/html
    depends_on:
      - laravel_mysql
    ports:
      - "9000:9000"
    networks:
      - sample_laravel