FROM node:12.20-alpine

WORKDIR /usr/src/app

COPY ../frontend/package.json /usr/src/app/package.json

RUN npm install 

RUN npm install -g @angular/cli@13.3.8

COPY ../frontend  /usr/src/app

CMD ng serve --host 0.0.0.0 --port 4200
